GAMELIST = [
    "crab_island",
    "crab_defense",
    "hack_attack",
    "pong_around",
    "witchwitchwitch",
    "pissbarrel",
    "jumpingbacteria",
    "walkingcrab",
    //"dawnville",
    "pooprun",
    "cursor_invasion",
    "fishing_for_humans",
    "nut_button",
    "pong",
]
